import type { StyleCase } from '../types/StyleCase'
import type {
  WallpaperCameraSpec,
  WallpaperEffectLayerType,
  WallpaperLayer,
} from '../types/WallpaperSpec'

const camera = (
  type: WallpaperCameraSpec['type'],
  zoom: number,
  speed: number,
  direction: WallpaperCameraSpec['direction'] = 'in',
  intensity = 1,
): WallpaperCameraSpec => ({
  enabled: type !== 'static',
  type,
  zoom,
  speed,
  direction,
  intensity,
})

const effectLayer = (
  id: string,
  name: string,
  type: WallpaperEffectLayerType,
  zIndex: number,
  settings: WallpaperLayer['settings'],
): WallpaperLayer => ({
  id,
  name,
  type,
  visible: true,
  locked: false,
  zIndex,
  settings,
})

export const STYLE_CASES: StyleCase[] = [
  {
    id: 'moonlight-ball',
    name: 'Moonlight Ball',
    description: 'Fantasy night ballroom atmosphere with blue moon glow.',
    previewEmoji: '\uD83C\uDF19',
    tags: ['night', 'fantasy', 'anime', 'blue'],
    recommendedScene: ['ballroom', 'castle', 'moonlit room', 'anime portrait'],
    camera: camera('breathing', 1.04, 1.1, 'in', 0.7),
    layers: [
      effectLayer('moonlight-ball-rays', 'Moonlight Rays', 'light_rays', 1, {
        count: 4,
        speed: 0.8,
        opacity: 0.34,
        variant: 'moonlight_rays',
        size: 1.15,
        blur: 1.5,
      }),
      effectLayer('moonlight-ball-glow', 'Blue Glow Particles', 'glow_particles', 2, {
        count: 54,
        speed: 0.8,
        opacity: 0.46,
        variant: 'bokeh',
        size: 1.05,
        color: '#9fdcff',
      }),
      effectLayer('moonlight-ball-stars', 'Distant Stars', 'stars', 3, {
        count: 78,
        speed: 0.7,
        opacity: 0.38,
        variant: 'twinkle',
      }),
      effectLayer('moonlight-ball-fog', 'Low Silver Fog', 'fog', 4, {
        count: 3,
        speed: 0.7,
        opacity: 0.18,
        variant: 'soft_mist',
        blur: 2,
      }),
    ],
  },
  {
    id: 'sakura-spring',
    name: 'Sakura Spring',
    description: 'Romantic spring breeze with soft petals and tiny light points.',
    previewEmoji: '\uD83C\uDF38',
    tags: ['spring', 'sakura', 'romantic'],
    recommendedScene: ['garden', 'street', 'anime landscape', 'daylight'],
    camera: camera('pan_left', 1.04, 0.8, 'left', 0.6),
    layers: [
      effectLayer('sakura-spring-petals', 'Sakura Petals', 'petals', 1, {
        count: 46,
        speed: 1.1,
        opacity: 0.42,
        variant: 'sakura',
        size: 1,
        direction: 'left',
      }),
      effectLayer('sakura-spring-glow', 'Spring Glow', 'glow_particles', 2, {
        count: 28,
        speed: 0.7,
        opacity: 0.28,
        variant: 'soft_glow',
        color: '#ffd7e6',
      }),
    ],
  },
  {
    id: 'fantasy-forest',
    name: 'Fantasy Forest',
    description: 'Magic forest ambience with fireflies, mist, and soft beams.',
    previewEmoji: '\uD83C\uDF32',
    tags: ['forest', 'magic', 'nature'],
    recommendedScene: ['forest', 'moss', 'ruins', 'nature path'],
    camera: camera('breathing', 1.05, 0.9, 'in', 0.75),
    layers: [
      effectLayer('fantasy-forest-fireflies', 'Forest Fireflies', 'fireflies', 1, {
        count: 44,
        speed: 0.9,
        opacity: 0.58,
        variant: 'warm_fireflies',
        size: 1.05,
      }),
      effectLayer('fantasy-forest-fog', 'Forest Mist', 'fog', 2, {
        count: 5,
        speed: 0.6,
        opacity: 0.24,
        variant: 'dream_haze',
        blur: 2.5,
      }),
      effectLayer('fantasy-forest-rays', 'Canopy Light Rays', 'light_rays', 3, {
        count: 3,
        speed: 0.8,
        opacity: 0.22,
        variant: 'fantasy_beams',
      }),
    ],
  },
  {
    id: 'snowy-night',
    name: 'Snowy Night',
    description: 'Quiet winter night with falling snow and thin cold fog.',
    previewEmoji: '\u2744\uFE0F',
    tags: ['snow', 'winter', 'night'],
    recommendedScene: ['winter street', 'cabin', 'night city', 'mountain'],
    camera: camera('static', 1, 1),
    layers: [
      effectLayer('snowy-night-snow', 'Heavy Night Snow', 'snow', 1, {
        count: 120,
        speed: 1.2,
        opacity: 0.62,
        variant: 'heavy_snow',
      }),
      effectLayer('snowy-night-fog', 'Cold Fog', 'fog', 2, {
        count: 3,
        speed: 0.55,
        opacity: 0.2,
        variant: 'low_fog',
        blur: 2,
      }),
    ],
  },
  {
    id: 'ocean-sunset',
    name: 'Ocean Sunset',
    description: 'Warm sunset light over the sea with slow cinematic pullback.',
    previewEmoji: '\uD83C\uDF05',
    tags: ['sunset', 'ocean', 'warm'],
    recommendedScene: ['beach', 'sea', 'coast', 'golden hour'],
    camera: camera('slow_zoom_out', 1.07, 0.8, 'out', 0.55),
    layers: [
      effectLayer('ocean-sunset-rays', 'Golden Rays', 'light_rays', 1, {
        count: 4,
        speed: 0.7,
        opacity: 0.36,
        variant: 'morning_rays',
        color: '#ffd38a',
      }),
      effectLayer('ocean-sunset-glow', 'Sunset Glow Dust', 'glow_particles', 2, {
        count: 36,
        speed: 0.7,
        opacity: 0.32,
        variant: 'magic_dust',
        color: '#ffc766',
      }),
    ],
  },
  {
    id: 'cyber-rain',
    name: 'Cyber Rain',
    description: 'Neon city rain with cool glow and lateral camera motion.',
    previewEmoji: '\uD83C\uDF27\uFE0F',
    tags: ['cyberpunk', 'city', 'rain'],
    recommendedScene: ['city', 'street', 'neon', 'night alley'],
    camera: camera('pan_right', 1.05, 1.2, 'right', 0.8),
    layers: [
      effectLayer('cyber-rain-rain', 'Neon Rain', 'rain', 1, {
        count: 140,
        speed: 2.5,
        opacity: 0.55,
        variant: 'neon_rain',
        direction: 'right',
      }),
      effectLayer('cyber-rain-glow', 'Neon Bokeh', 'glow_particles', 2, {
        count: 52,
        speed: 0.9,
        opacity: 0.42,
        variant: 'bokeh',
        color: '#35d6ff',
      }),
    ],
  },
  {
    id: 'starry-sky',
    name: 'Starry Sky',
    description: 'Space dream scene with galaxy dust and quiet glow.',
    previewEmoji: '\u2B50',
    tags: ['space', 'night', 'dream'],
    recommendedScene: ['sky', 'space', 'mountains', 'window view'],
    camera: camera('static', 1, 1),
    layers: [
      effectLayer('starry-sky-stars', 'Galaxy Stars', 'stars', 1, {
        count: 150,
        speed: 0.8,
        opacity: 0.68,
        variant: 'galaxy_dust',
        blur: 0.5,
      }),
      effectLayer('starry-sky-glow', 'Galaxy Glow', 'glow_particles', 2, {
        count: 42,
        speed: 0.45,
        opacity: 0.32,
        variant: 'bokeh',
        size: 1.3,
        color: '#92b7ff',
      }),
    ],
  },
  {
    id: 'dream-garden',
    name: 'Dream Garden',
    description: 'Soft fantasy garden with flowers, fireflies, and luminous dust.',
    previewEmoji: '\uD83C\uDF3A',
    tags: ['dreamy', 'flowers', 'fantasy'],
    recommendedScene: ['garden', 'flowers', 'fantasy path', 'greenhouse'],
    camera: camera('breathing', 1.04, 0.85, 'in', 0.65),
    layers: [
      effectLayer('dream-garden-petals', 'Tiny Flowers', 'petals', 1, {
        count: 34,
        speed: 0.85,
        opacity: 0.34,
        variant: 'tiny_flowers',
      }),
      effectLayer('dream-garden-fireflies', 'Fairy Lights', 'fireflies', 2, {
        count: 38,
        speed: 0.8,
        opacity: 0.5,
        variant: 'fairy_lights',
      }),
      effectLayer('dream-garden-glow', 'Dream Glow', 'glow_particles', 3, {
        count: 46,
        speed: 0.7,
        opacity: 0.36,
        variant: 'magic_dust',
        color: '#ffe6a7',
      }),
    ],
  },
]
